services:
  frontend:
    build: ./readmeister-frontend
    image: readmeister-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./readmeister-backend
    image: readmeister-backend
    ports:
      - "8081:1001"
    environment:
      - PORT=1001
      - MONGODB_URI=your_atlas_url
      - GITHUB_CLIENT_ID=...
      - GITHUB_CLIENT_SECRET=...
      - GITHUB_REDIRECT_URI=...
      - GEMINI_API_KEY=...